version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
      # target: development
    tty: true
    ports:
      - '8080:8080'
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0.27
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bigami
      MYSQL_DATABASE: bigami
      MYSQL_USER: bigami
      MYSQL_PASSWORD: bigami
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: