// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LowerSchool struct {
	ID       string `json:"id"`
	SchoolID string `json:"school_id"`
	Name     string `json:"name"`
	Style    string `json:"style"`
	Enemy    string `json:"enemy"`
}

type School struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Style string `json:"style"`
	Enemy string `json:"enemy"`
}
