// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSchools(t *testing.T) {
	t.Parallel()

	query := Schools()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSchoolsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSchoolsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Schools().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSchoolsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SchoolSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSchoolsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SchoolExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if School exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SchoolExists to return true, but got false.")
	}
}

func testSchoolsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	schoolFound, err := FindSchool(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if schoolFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSchoolsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Schools().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSchoolsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Schools().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSchoolsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	schoolOne := &School{}
	schoolTwo := &School{}
	if err = randomize.Struct(seed, schoolOne, schoolDBTypes, false, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}
	if err = randomize.Struct(seed, schoolTwo, schoolDBTypes, false, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = schoolOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = schoolTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Schools().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSchoolsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	schoolOne := &School{}
	schoolTwo := &School{}
	if err = randomize.Struct(seed, schoolOne, schoolDBTypes, false, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}
	if err = randomize.Struct(seed, schoolTwo, schoolDBTypes, false, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = schoolOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = schoolTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func schoolBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func schoolAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *School) error {
	*o = School{}
	return nil
}

func testSchoolsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &School{}
	o := &School{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, schoolDBTypes, false); err != nil {
		t.Errorf("Unable to randomize School object: %s", err)
	}

	AddSchoolHook(boil.BeforeInsertHook, schoolBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	schoolBeforeInsertHooks = []SchoolHook{}

	AddSchoolHook(boil.AfterInsertHook, schoolAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	schoolAfterInsertHooks = []SchoolHook{}

	AddSchoolHook(boil.AfterSelectHook, schoolAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	schoolAfterSelectHooks = []SchoolHook{}

	AddSchoolHook(boil.BeforeUpdateHook, schoolBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	schoolBeforeUpdateHooks = []SchoolHook{}

	AddSchoolHook(boil.AfterUpdateHook, schoolAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	schoolAfterUpdateHooks = []SchoolHook{}

	AddSchoolHook(boil.BeforeDeleteHook, schoolBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	schoolBeforeDeleteHooks = []SchoolHook{}

	AddSchoolHook(boil.AfterDeleteHook, schoolAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	schoolAfterDeleteHooks = []SchoolHook{}

	AddSchoolHook(boil.BeforeUpsertHook, schoolBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	schoolBeforeUpsertHooks = []SchoolHook{}

	AddSchoolHook(boil.AfterUpsertHook, schoolAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	schoolAfterUpsertHooks = []SchoolHook{}
}

func testSchoolsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSchoolsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(schoolColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSchoolToManyLowerSchools(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a School
	var b, c LowerSchool

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, lowerSchoolDBTypes, false, lowerSchoolColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, lowerSchoolDBTypes, false, lowerSchoolColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.SchoolID = a.ID
	c.SchoolID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.LowerSchools().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.SchoolID == b.SchoolID {
			bFound = true
		}
		if v.SchoolID == c.SchoolID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SchoolSlice{&a}
	if err = a.L.LoadLowerSchools(ctx, tx, false, (*[]*School)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.LowerSchools); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.LowerSchools = nil
	if err = a.L.LoadLowerSchools(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.LowerSchools); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSchoolToManyAddOpLowerSchools(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a School
	var b, c, d, e LowerSchool

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, schoolDBTypes, false, strmangle.SetComplement(schoolPrimaryKeyColumns, schoolColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*LowerSchool{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lowerSchoolDBTypes, false, strmangle.SetComplement(lowerSchoolPrimaryKeyColumns, lowerSchoolColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*LowerSchool{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddLowerSchools(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.SchoolID {
			t.Error("foreign key was wrong value", a.ID, first.SchoolID)
		}
		if a.ID != second.SchoolID {
			t.Error("foreign key was wrong value", a.ID, second.SchoolID)
		}

		if first.R.School != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.School != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.LowerSchools[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.LowerSchools[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.LowerSchools().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSchoolsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSchoolsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SchoolSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSchoolsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Schools().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	schoolDBTypes = map[string]string{`ID`: `int`, `Name`: `varchar`, `Style`: `text`, `Enemy`: `varchar`}
	_             = bytes.MinRead
)

func testSchoolsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(schoolPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(schoolAllColumns) == len(schoolPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSchoolsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(schoolAllColumns) == len(schoolPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &School{}
	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, schoolDBTypes, true, schoolPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(schoolAllColumns, schoolPrimaryKeyColumns) {
		fields = schoolAllColumns
	} else {
		fields = strmangle.SetComplement(
			schoolAllColumns,
			schoolPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SchoolSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSchoolsUpsert(t *testing.T) {
	t.Parallel()

	if len(schoolAllColumns) == len(schoolPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLSchoolUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := School{}
	if err = randomize.Struct(seed, &o, schoolDBTypes, false); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert School: %s", err)
	}

	count, err := Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, schoolDBTypes, false, schoolPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize School struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert School: %s", err)
	}

	count, err = Schools().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
